### ISSUE TITLE
cmfive.php setup script bug

### ISSUE THREAD

**Issue by twje** [2pisoftware/cmfive-boilerplate#7]
**Issue**

The cmfive.php setup script presents ordered steps through 1 to 4:

**Step 1.** uses composer to dynamically install php packages. 

**Step 2.** in the same PHP session, step 2 attempts to perform database migrations. However the autoloader class is already instantiated from Step 1 and does not observe the newly added packages. 

This results in a class not found:

**Stack Trace**
```
PHP Fatal error:  Uncaught Error: Class 'Phinx\Db\Adapter\MysqlAdapter' not found in /var/www/html/composer/vendor/2pisoftware/cmfive-core/system/modules/admin/models/MigrationService.php:550
Stack trace:
#0 /var/www/html/cmfive.php(337): MigrationService->installInitialMigration()
#1 /var/www/html/cmfive.php(104): installMigrations()
#2 {main}
  thrown in /var/www/html/composer/vendor/2pisoftware/cmfive-core/system/modules/admin/models/MigrationService.php on line 550

Fatal error: Uncaught Error: Class 'Phinx\Db\Adapter\MysqlAdapter' not found in /var/www/html/composer/vendor/2pisoftware/cmfive-core/system/modules/admin/models/MigrationService.php on line 550

Error: Class 'Phinx\Db\Adapter\MysqlAdapter' not found in /var/www/html/composer/vendor/2pisoftware/cmfive-core/system/modules/admin/models/MigrationService.php on line 550

Call Stack:
    0.0013     448008   1. {main}() /var/www/html/cmfive.php:0
   72.5990    2310840   2. installMigrations() /var/www/html/cmfive.php:104
   72.6581    2478720   3. MigrationService->installInitialMigration() /var/www/html/cmfive.php:337
   
   
$mysql_adapter = new \Phinx\Db\Adapter\MysqlAdapter([
    'connection' => $this->w->db,
    'name' => Config::get('database.database')
])
```
**Workaround**

After performing Step 1, exit the script and run it again to perform Step 2.

**Todo**

Investigate permanent fix

**Comment by DerekCrannaford** [comment]
Nominal fix for proving:

 - As stands:
  -> allow composer core/git install -> require composer autoloader -> instance of web -> install composer module dependencies
  -> Problem = migration step now has autoloader already in place, but instance was constructed prior to modules installed
  -> instance of web -> get migration models -> fail to install, no DB supporting libs in autoloader lookup

 - Fix:
  -> patch code for getting "instance of web" -> find composer autoloader class -> reload (at least) psr4 lookups -> get migration models -> install OK, with DB supporting libs from psr4 autoloader lookup

**Comment by DerekCrannaford** [comment]
Patch function like:
~~~
if (strpos($class, "ComposerAutoloaderInit") !== false) {
                $composerLoader = $class;
                $map = require 'composer/vendor/composer/autoload_psr4.php';
                foreach ($map as $namespace => $path) {
                    $composerLoader::getLoader()->setPsr4($namespace, $path);
                }
~~~
